name: "bioconda-utils-build-env-cos7"
on:
  pull_request:
    paths:
    - .github/workflows/bioconda-utils-build-env-cos7.yml
    - .github/workflows/generic_build.yml

jobs:
  bioconda-utils-build-env-cos7:
    uses: bioconda/bioconda-containers/.github/workflows/generic_build.yml@reusable-workflow-testing
    with:
      image_name: bioconda-utils-build-env-cos7
      tags: '3.1 3 latest'
      debian_version: '12.2'
      archs: 'arm64 amd64'
