name: "Generic caller test"
on:
  pull_request:
    paths:
    - .github/workflows/caller.yml

jobs:
  base-glibc-debian-bash:
    uses: bioconda/bioconda-containers/.github/workflows/generic_build.yml@reusable-workflow-testing
    with:
      image_name: base-glibc-debian-bash
      tags: '3.1 3 latest'
      build_args: '--build-arg=debian_version=12.2'

  base-glibc-busybox-bash:
    uses: bioconda/bioconda-containers/.github/workflows/generic_build.yml@reusable-workflow-testing
    with:
      image_name: base-glibc-busybox-bash
      tags: '3.1 3 latest'
      build_args: '--build-arg=debian_version=12.2 --build-arg=busybox_version=1.36.1'
